VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "CentOS7.0"

  config.vm.define :node1 do |node|
    node.vm.box = "CentOS7.0"
    node.vm.network :forwarded_port, guest: 22, host: 2001, id: "ssh"
    node.vm.network :private_network, ip: "192.168.33.11", virtualbox__intnet: "private_net"
  end

  config.vm.define :node2 do |node|
    node.vm.box = "CentOS7.0"
    node.vm.network :forwarded_port, guest: 22, host: 2002, id: "ssh"
    node.vm.network :forwarded_port, guest: 80, host: 8000, id: "http"
    node.vm.network :private_network, ip: "192.168.33.12", virtualbox__intnet: "private_net"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.inventory_path = "provisioning/hosts"
    ansible.playbook = "provisioning/site.yml"
    ansible.limit = 'all'
  end
end
